#!/bin/bash

echo "========================================="
echo "Frontend Configuration Setup"
echo "========================================="

# Get the stack outputs
echo "Getting API endpoints from AWS..."

# Get Main API endpoint
MAIN_API=$(aws cloudformation describe-stacks \
  --stack-name RsvpBackendStack \
  --region us-east-1 \
  --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" \
  --output text 2>/dev/null)

# Get Admin API endpoint
ADMIN_API=$(aws cloudformation describe-stacks \
  --stack-name RsvpBackendStack \
  --region us-east-1 \
  --query "Stacks[0].Outputs[?OutputKey=='AdminApiEndpoint'].OutputValue" \
  --output text 2>/dev/null)

if [ -z "$ADMIN_API" ]; then
  echo "❌ Could not find Admin API endpoint"
  echo "Make sure the RsvpBackendStack is deployed: npx cdk deploy RsvpBackendStack"
  exit 1
fi

# Create .env.local file
cat > frontend/.env.local << EOF
# Auto-generated by setup-frontend.sh
# Generated at: $(date)

# Main RSVP API
REACT_APP_API_URL=$MAIN_API

# Admin API
REACT_APP_ADMIN_API_URL=$ADMIN_API

# Environment
REACT_APP_ENVIRONMENT=development
EOF

echo "✅ Frontend configuration created!"
echo ""
echo "API Endpoints:"
echo "  Main API:  $MAIN_API"
echo "  Admin API: $ADMIN_API"
echo ""
echo "Configuration saved to: frontend/.env.local"
echo ""
echo "Now run:"
echo "  cd frontend"
echo "  npm install"
echo "  npm start"
echo ""
echo "Then login at: http://localhost:3000/admin/login"